# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 04:53
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20, verbose_name='Estado')),
                ('municipality', models.CharField(max_length=50, verbose_name='Municipio/delegación')),
                ('suburb', models.CharField(max_length=50, verbose_name='Colonia')),
                ('street', models.CharField(max_length=70, verbose_name='Calle')),
                ('outdoor_number', models.IntegerField(default=0, verbose_name='Numero exterior')),
                ('zipcode', models.IntegerField(default=0, verbose_name='codigo postal')),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Administrador',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CostomerServiceUser',
            fields=[
            ],
            options={
                'verbose_name': 'Servicio al cliente',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'verbose_name': 'staff',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_relationship_address', related_query_name='client_relationship_address', to='users.ClientUser', verbose_name='Cliente'),
        ),
    ]
