# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170926_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'permissions': (('view_address', 'can see address'),)},
        ),
        migrations.AlterModelOptions(
            name='clientuser',
            options={'permissions': (('view_clientuser', 'can see client user'),), 'verbose_name': 'Cliente'},
        ),
    ]
